export interface AiPersonality {
  id: string;
  name: string;
  tagline: string;

  // --- economia / gestione dei Risikon ---
  /** R sempre tenuti da parte, mai spesi in armate (cuscinetto di sicurezza) */
  currencyReserve: number;
  /** se impostata, l'IA non compra nulla finché non accumula almeno questa cifra,
   *  poi la spende tutta in un colpo solo (l'"agguato"): null = compra regolarmente ogni turno */
  ambushThreshold: number | null;

  // --- aggressività / rischio in attacco ---
  /** probabilità minima (0..1) di conquistare il territorio, calcolata esattamente sulla
   *  meccanica dei dadi, perché l'attacco sia considerato conveniente */
  minWinProbability: number;
  /** non attacca mai da un territorio che ha meno (o uguale) di queste armate: quanto presidio minimo vuole sempre lasciarsi */
  minArmiesToKeepAttacking: number;
  /** 0..1: quanta casualità nella scelta del bersaglio tra le opzioni migliori (0 = sempre la scelta ottima) */
  randomness: number;

  // --- focus strategico ---
  /** 0..1: peso dato al completare/consolidare un continente */
  continentFocus: number;
  /** 0..1: peso dato all'attaccare il giocatore attualmente in testa alla partita */
  targetLeaderBias: number;
  /** 0..1: peso dato a finire un avversario abbastanza debole da poter essere eliminato
   *  del tutto in questo turno, per ereditarne riserva e Risikon (stile "caccia al debole") */
  huntWeakBias: number;
  /** 0..1: quota (tra il minimo obbligatorio e il massimo possibile) di armate spostate dopo una conquista */
  conquestOverstack: number;
  /** 0..1: quanta priorità dà al rinforzare i fronti deboli invece di espandersi liberamente */
  defensiveBias: number;

  // --- consapevolezza del rivale / modalità esecutore ---
  /** 0..1: peso extra dato a bersagli controllati da un giocatore umano (invece che da un'altra IA),
   *  sia come priorità di attacco/rinforzo sia come disponibilità a rischiare di più contro di lui */
  vsHumanBias: number;
  /** quante volte le proprie armate totali devono superare quelle del rivale più forte rimasto perché
   *  l'IA smetta di giocare in modo prudente e passi alla "modalità esecutore": individua il rivale più
   *  debole rimasto (o l'unico umano superstite) e lo insegue senza tregua per chiudere la partita,
   *  invece di continuare a giocare in modo conservativo all'infinito */
  finisherThreshold: number;
}

export const PERSONALITIES: AiPersonality[] = [
  {
    id: "alessandro",
    name: "Alessandro Magno",
    tagline: "Conquista tutto ciò che vede, senza mai fermarsi.",
    currencyReserve: 0,
    ambushThreshold: null,
    minWinProbability: 0.45,
    minArmiesToKeepAttacking: 1,
    randomness: 0.1,
    continentFocus: 0.8,
    targetLeaderBias: 0.2,
    huntWeakBias: 0.6,
    conquestOverstack: 0.8,
    defensiveBias: 0.2,
    vsHumanBias: 0.3,
    finisherThreshold: 2.2,
  },
  {
    id: "napoleone",
    name: "Napoleone Bonaparte",
    tagline: "Accumula risorse in silenzio, poi colpisce con forza schiacciante.",
    currencyReserve: 100,
    ambushThreshold: 700,
    minWinProbability: 0.55,
    minArmiesToKeepAttacking: 2,
    randomness: 0.15,
    continentFocus: 0.5,
    targetLeaderBias: 0.6,
    huntWeakBias: 0.7,
    conquestOverstack: 0.9,
    defensiveBias: 0.4,
    vsHumanBias: 0.5,
    finisherThreshold: 2.5,
  },
  {
    id: "gengis_khan",
    name: "Gengis Khan",
    tagline: "Non si ferma mai: ogni fronte è un'occasione per razziare.",
    currencyReserve: 0,
    ambushThreshold: null,
    minWinProbability: 0.35,
    minArmiesToKeepAttacking: 1,
    randomness: 0.05,
    continentFocus: 0.3,
    targetLeaderBias: 0.1,
    huntWeakBias: 0.9,
    conquestOverstack: 0.3,
    defensiveBias: 0.1,
    vsHumanBias: 0.4,
    finisherThreshold: 2.0,
  },
  {
    id: "sun_tzu",
    name: "Sun Tzu",
    tagline: "Attacca solo quando la vittoria è già certa.",
    currencyReserve: 200,
    ambushThreshold: 500,
    minWinProbability: 0.75,
    minArmiesToKeepAttacking: 3,
    randomness: 0.05,
    continentFocus: 0.6,
    targetLeaderBias: 0.4,
    huntWeakBias: 0.6,
    conquestOverstack: 0.5,
    defensiveBias: 0.7,
    vsHumanBias: 0.6,
    finisherThreshold: 3.2,
  },
  {
    id: "annibale",
    name: "Annibale Barca",
    tagline: "Aggira le difese e colpisce dove non te lo aspetti.",
    currencyReserve: 50,
    ambushThreshold: null,
    minWinProbability: 0.4,
    minArmiesToKeepAttacking: 1,
    randomness: 0.35,
    continentFocus: 0.3,
    targetLeaderBias: 0.3,
    huntWeakBias: 0.5,
    conquestOverstack: 0.4,
    defensiveBias: 0.3,
    vsHumanBias: 0.35,
    finisherThreshold: 2.4,
  },
  {
    id: "cesare",
    name: "Giulio Cesare",
    tagline: "Conquista con metodo, continente dopo continente.",
    currencyReserve: 100,
    ambushThreshold: null,
    minWinProbability: 0.5,
    minArmiesToKeepAttacking: 2,
    randomness: 0.1,
    continentFocus: 0.9,
    targetLeaderBias: 0.7,
    huntWeakBias: 0.5,
    conquestOverstack: 0.6,
    defensiveBias: 0.5,
    vsHumanBias: 0.4,
    finisherThreshold: 2.6,
  },
  {
    id: "rommel",
    name: "Erwin Rommel",
    tagline: "Sposta le sue truppe dove serve, prima che il nemico se ne accorga.",
    currencyReserve: 50,
    ambushThreshold: null,
    minWinProbability: 0.45,
    minArmiesToKeepAttacking: 2,
    randomness: 0.25,
    continentFocus: 0.4,
    targetLeaderBias: 0.3,
    huntWeakBias: 0.4,
    conquestOverstack: 0.5,
    defensiveBias: 0.8,
    vsHumanBias: 0.3,
    finisherThreshold: 2.5,
  },
  {
    id: "kutuzov",
    name: "Kutuzov",
    tagline: "Aspetta, si difende, e colpisce solo quando il nemico è sfinito.",
    currencyReserve: 300,
    ambushThreshold: 900,
    minWinProbability: 0.78,
    minArmiesToKeepAttacking: 3,
    randomness: 0.05,
    continentFocus: 0.2,
    targetLeaderBias: 0.5,
    huntWeakBias: 0.3,
    conquestOverstack: 0.8,
    defensiveBias: 0.9,
    vsHumanBias: 0.7,
    finisherThreshold: 3.5,
  },
  {
    id: "custer",
    name: "Custer",
    tagline: "Carica sempre, a qualunque costo.",
    currencyReserve: 0,
    ambushThreshold: null,
    minWinProbability: 0.15,
    minArmiesToKeepAttacking: 1,
    randomness: 0.4,
    continentFocus: 0.1,
    targetLeaderBias: 0,
    huntWeakBias: 0.5,
    conquestOverstack: 0.9,
    defensiveBias: 0,
    vsHumanBias: 0.2,
    finisherThreshold: 1.6,
  },
  {
    id: "vercingetorige",
    name: "Vercingetorige",
    tagline: "Difende la sua terra e si scaglia su chiunque diventi troppo forte.",
    currencyReserve: 100,
    ambushThreshold: null,
    minWinProbability: 0.42,
    minArmiesToKeepAttacking: 2,
    randomness: 0.2,
    continentFocus: 0.2,
    targetLeaderBias: 0.9,
    huntWeakBias: 0.3,
    conquestOverstack: 0.4,
    defensiveBias: 0.9,
    vsHumanBias: 0.5,
    finisherThreshold: 2.8,
  },
  {
    id: "attila",
    name: "Attila",
    tagline: "Semina il terrore: nessun confine è mai abbastanza lontano per lui.",
    currencyReserve: 0,
    ambushThreshold: null,
    minWinProbability: 0.3,
    minArmiesToKeepAttacking: 1,
    randomness: 0.15,
    continentFocus: 0.15,
    targetLeaderBias: 0.2,
    huntWeakBias: 0.85,
    conquestOverstack: 0.3,
    defensiveBias: 0.05,
    vsHumanBias: 0.3,
    finisherThreshold: 1.8,
  },
  {
    id: "saladino",
    name: "Saladino",
    tagline: "Magnanimo in pace, spietato quando la giustizia lo richiede.",
    currencyReserve: 150,
    ambushThreshold: null,
    minWinProbability: 0.6,
    minArmiesToKeepAttacking: 2,
    randomness: 0.1,
    continentFocus: 0.5,
    targetLeaderBias: 0.6,
    huntWeakBias: 0.2,
    conquestOverstack: 0.5,
    defensiveBias: 0.75,
    vsHumanBias: 0.45,
    finisherThreshold: 2.7,
  },
  {
    id: "federico",
    name: "Federico il Grande",
    tagline: "Ogni mossa calcolata come una manovra su un campo di parata.",
    currencyReserve: 120,
    ambushThreshold: null,
    minWinProbability: 0.58,
    minArmiesToKeepAttacking: 2,
    randomness: 0.05,
    continentFocus: 0.7,
    targetLeaderBias: 0.5,
    huntWeakBias: 0.4,
    conquestOverstack: 0.6,
    defensiveBias: 0.6,
    vsHumanBias: 0.5,
    finisherThreshold: 2.6,
  },
  {
    id: "nevskij",
    name: "Alessandro Nevskij",
    tagline: "Lascia che il nemico si sfianchi sul ghiaccio, poi lo travolge.",
    currencyReserve: 250,
    ambushThreshold: null,
    minWinProbability: 0.7,
    minArmiesToKeepAttacking: 3,
    randomness: 0.05,
    continentFocus: 0.3,
    targetLeaderBias: 0.4,
    huntWeakBias: 0.3,
    conquestOverstack: 0.7,
    defensiveBias: 0.95,
    vsHumanBias: 0.65,
    finisherThreshold: 3.4,
  },
  {
    id: "wellington",
    name: "Wellington",
    tagline: "Resiste dietro la collina finché il nemico non si spezza da solo.",
    currencyReserve: 150,
    ambushThreshold: 550,
    minWinProbability: 0.62,
    minArmiesToKeepAttacking: 3,
    randomness: 0.05,
    continentFocus: 0.3,
    targetLeaderBias: 0.85,
    huntWeakBias: 0.25,
    conquestOverstack: 0.5,
    defensiveBias: 0.8,
    vsHumanBias: 0.7,
    finisherThreshold: 3.0,
  },
  {
    id: "patton",
    name: "Patton",
    tagline: "Avanti sempre: non ti fermare mai a consolidare.",
    currencyReserve: 20,
    ambushThreshold: null,
    minWinProbability: 0.4,
    minArmiesToKeepAttacking: 1,
    randomness: 0.1,
    continentFocus: 0.3,
    targetLeaderBias: 0.7,
    huntWeakBias: 0.5,
    conquestOverstack: 0.9,
    defensiveBias: 0.1,
    vsHumanBias: 0.4,
    finisherThreshold: 2.0,
  },
  {
    id: "zhukov",
    name: "Zhukov",
    tagline: "Accumula un'armata immensa, poi la scaglia tutta in un colpo solo.",
    currencyReserve: 80,
    ambushThreshold: 800,
    minWinProbability: 0.55,
    minArmiesToKeepAttacking: 2,
    randomness: 0.05,
    continentFocus: 0.4,
    targetLeaderBias: 0.5,
    huntWeakBias: 0.6,
    conquestOverstack: 0.85,
    defensiveBias: 0.5,
    vsHumanBias: 0.55,
    finisherThreshold: 2.8,
  },
  {
    id: "nobunaga",
    name: "Oda Nobunaga",
    tagline: "Unifica con il ferro ciò che la diplomazia non riesce a piegare.",
    currencyReserve: 60,
    ambushThreshold: null,
    minWinProbability: 0.48,
    minArmiesToKeepAttacking: 2,
    randomness: 0.1,
    continentFocus: 0.85,
    targetLeaderBias: 0.6,
    huntWeakBias: 0.4,
    conquestOverstack: 0.6,
    defensiveBias: 0.4,
    vsHumanBias: 0.35,
    finisherThreshold: 2.5,
  },
  {
    id: "boudica",
    name: "Boudica",
    tagline: "La vendetta guida ogni sua carica, senza calcolo né pietà.",
    currencyReserve: 0,
    ambushThreshold: null,
    minWinProbability: 0.25,
    minArmiesToKeepAttacking: 1,
    randomness: 0.4,
    continentFocus: 0.1,
    targetLeaderBias: 0.9,
    huntWeakBias: 0.3,
    conquestOverstack: 0.4,
    defensiveBias: 0.15,
    vsHumanBias: 0.6,
    finisherThreshold: 1.7,
  },
  {
    id: "tamerlano",
    name: "Tamerlano",
    tagline: "Non lascia nulla alle spalle: chi è debole viene cancellato.",
    currencyReserve: 30,
    ambushThreshold: null,
    minWinProbability: 0.35,
    minArmiesToKeepAttacking: 1,
    randomness: 0.1,
    continentFocus: 0.3,
    targetLeaderBias: 0.3,
    huntWeakBias: 0.95,
    conquestOverstack: 0.7,
    defensiveBias: 0.15,
    vsHumanBias: 0.4,
    finisherThreshold: 1.9,
  },
];

const DEFAULT_PERSONALITY: AiPersonality = {
  id: "recluta",
  name: "Recluta",
  tagline: "Un soldato senza scuola: gioca in modo prevedibile e bilanciato.",
  currencyReserve: 0,
  ambushThreshold: null,
  minWinProbability: 0.5,
  minArmiesToKeepAttacking: 1,
  randomness: 0,
  continentFocus: 0,
  targetLeaderBias: 0,
  huntWeakBias: 0.3,
  conquestOverstack: 0.3,
  defensiveBias: 0.5,
  vsHumanBias: 0.2,
  finisherThreshold: 3.0,
};

export function personalityById(id: string | null | undefined): AiPersonality {
  return PERSONALITIES.find((p) => p.id === id) ?? DEFAULT_PERSONALITY;
}

/** Sceglie una personalità storica non ancora usata nella stanza, se possibile. */
export function pickUnusedPersonality(usedIds: (string | null | undefined)[]): AiPersonality {
  const used = new Set(usedIds.filter(Boolean));
  const available = PERSONALITIES.filter((p) => !used.has(p.id));
  const pool = available.length > 0 ? available : PERSONALITIES;
  return pool[Math.floor(Math.random() * pool.length)];
}
